from __future__ import annotations

import re
import shutil
import subprocess
import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from fastapi.testclient import TestClient

from arangur.app.main import create_app
from arangur.app.settings import APP_NAME, AppSettings, load_settings


class AppHealthTests(unittest.TestCase):
    def test_health_returns_default_local_status(self) -> None:
        client = TestClient(create_app(settings=AppSettings()))
        response = client.get("/api/health")
        self.assertEqual(200, response.status_code)
        payload = response.json()
        self.assertEqual("ok", payload["status"])
        self.assertEqual(APP_NAME, payload["app"])
        self.assertEqual("local", payload["app_env"])
        self.assertEqual("local", payload["runtime_mode"])
        self.assertEqual("none", payload["db_engine"])
        self.assertFalse(payload["database_configured"])
        self.assertFalse(payload["demo_admin_token_configured"])

    def test_private_demo_settings_parse_environment_without_requiring_secrets(self) -> None:
        settings = load_settings(
            {
                "APP_ENV": "private_demo",
                "PUBLIC_ORIGIN": "https://demo.example.test",
                "ALLOWED_ORIGINS": "https://demo.example.test, http://localhost:8000",
                "DB_ENGINE": "none",
            }
        )
        self.assertEqual("private_demo", settings.app_env)
        self.assertEqual("private_demo", settings.runtime_mode)
        self.assertEqual("https://demo.example.test", settings.public_origin)
        self.assertEqual(("https://demo.example.test", "http://localhost:8000"), settings.allowed_origins)
        self.assertFalse(settings.demo_admin_token_configured)
        self.assertFalse(settings.database_url_configured)

    def test_private_demo_health_does_not_require_admin_token(self) -> None:
        client = TestClient(create_app(settings=AppSettings(app_env="private_demo", db_engine="none")))
        response = client.get("/api/health")
        self.assertEqual(200, response.status_code)
        payload = response.json()
        self.assertEqual("private_demo", payload["app_env"])
        self.assertEqual("private_demo", payload["runtime_mode"])
        self.assertFalse(payload["demo_admin_token_configured"])

    def test_root_page_returns_report_element_spec_composer(self) -> None:
        client = TestClient(create_app(settings=AppSettings()))
        for path in ("/", "/app/", "/app/index.html"):
            with self.subTest(path=path):
                response = client.get(path)
                self.assertEqual(200, response.status_code)
                self.assertIn("text/html", response.headers["content-type"])
                self.assertIn("Arangur", response.text)
                self.assertIn("Advisor Home", response.text)
                self.assertIn("Manage briefing workflows", response.text)
                self.assertIn("Create a new workflow", response.text)
                self.assertIn("Work with an existing workflow", response.text)
                self.assertIn("Populate a workflow with data", response.text)
                self.assertIn("Present / view reports", response.text)
                self.assertIn("New Client Briefing Workflow", response.text)
                self.assertIn("New Advisor Review Workflow", response.text)
                self.assertIn("No saved workflows yet. Create a new workflow first.", response.text)
                self.assertNotIn("home-open-saved-button", response.text)
                self.assertNotIn("Open saved workflow", response.text)
                self.assertNotIn("Copy existing workflow", response.text)
                self.assertIn("Workflow name", response.text)
                self.assertIn("Save current workflow", response.text)
                self.assertIn("Copy Workflow", response.text)
                self.assertIn("Unsaved current work", response.text)
                self.assertIn("Developer / QA tools", response.text)
                self.assertIn("Open Developer / QA tools", response.text)
                self.assertIn("Full dated report generation and persistence are not implemented yet.", response.text)
                self.assertIn("Choose a saved workflow and open a clean Presentation view using the current demo preview renderer.", response.text)
                self.assertIn("LOCAL_WORKFLOW_STORAGE_KEY", response.text)
                self.assertIn("localStorage", response.text)
                self.assertIn("display_name", response.text)
                self.assertIn("workflow_id", response.text)
                self.assertIn("storage_key", response.text)
                self.assertIn("readableWorkflowName", response.text)
                self.assertIn("normalizeSavedWorkflowRecord", response.text)
                self.assertIn("workflowDisplayName", response.text)
                self.assertIn("workflow_name: name", response.text)
                self.assertIn("`${baseName} Copy`", response.text)
                self.assertIn("`${workflowDisplayName(workflow)} Copy`", response.text)
                self.assertIn("saveCurrentWorkflow", response.text)
                self.assertIn("openSavedWorkflow", response.text)
                self.assertIn("openWorkflowActionMode", response.text)
                self.assertIn("duplicateSavedWorkflow", response.text)
                self.assertIn("deleteSavedWorkflow", response.text)
                self.assertIn("loadLocalNamedWorkflows", response.text)
                self.assertIn('body class="app-route-home"', response.text)
                self.assertIn('"#home"', response.text)
                self.assertIn('"#workflow/create"', response.text)
                self.assertIn('"#workflow/existing"', response.text)
                self.assertIn('"#workflow/populate"', response.text)
                self.assertIn('"#workflow/present"', response.text)
                self.assertIn('"#builder"', response.text)
                self.assertIn('"#populate"', response.text)
                self.assertIn('"#presentation"', response.text)
                self.assertIn('"#preview/client"', response.text)
                self.assertIn('"#preview/advisor"', response.text)
                self.assertIn('"#advanced"', response.text)
                self.assertIn("app-route-workflow-mode", response.text)
                self.assertIn("HOME_MODE_ROUTES", response.text)
                self.assertIn("HOME_MODE_ROUTE_BY_MODE", response.text)
                self.assertIn("navigateToRoute", response.text)
                self.assertIn("replaceRoute", response.text)
                self.assertIn("applyRoute", response.text)
                self.assertIn("routeFromHash", response.text)
                self.assertIn("window.location.hash", response.text)
                self.assertIn('window.addEventListener("hashchange"', response.text)
                self.assertIn("window.history.replaceState", response.text)
                self.assertIn("Report element finder", response.text)
                self.assertIn("Choose a target set, then find an element", response.text)
                self.assertIn("Search report elements", response.text)
                self.assertIn("Browse category", response.text)
                self.assertIn("Guided filter", response.text)
                self.assertIn("Browse all templates", response.text)
                self.assertIn("All report element templates grouped by category", response.text)
                self.assertIn("browse-picker", response.text)
                self.assertIn('aria-controls="browse-all-panel"', response.text)
                self.assertIn('aria-expanded="false"', response.text)
                self.assertIn('role="menu"', response.text)
                self.assertIn('class="browse-category-row"', response.text)
                self.assertIn("browse-template-row", response.text)
                self.assertIn('role="menuitem"', response.text)
                self.assertIn("Search, browse a category, or choose a filter to find report elements.", response.text)
                self.assertIn("Compact candidate report elements", response.text)
                self.assertIn("Select a report element to see details.", response.text)
                self.assertIn("Add narrative element", response.text)
                self.assertIn("Narrative element", response.text)
                self.assertIn("Section title", response.text)
                self.assertIn("Short explanation", response.text)
                self.assertIn("Discussion prompt", response.text)
                self.assertIn("Speaker note", response.text)
                self.assertIn("Working note", response.text)
                self.assertIn("Diagnostic comment", response.text)
                self.assertIn("Follow-up item", response.text)
                self.assertIn("Client-prep note", response.text)
                self.assertIn('CATALOG_ENDPOINT = "/api/report-elements"', response.text)
                self.assertIn("fetch(CATALOG_ENDPOINT)", response.text)
                self.assertIn("Client Briefing Workflow", response.text)
                self.assertIn("Advisor Review Workflow", response.text)
                self.assertIn("Preview Client Briefing", response.text)
                self.assertIn("Preview Advisor Review", response.text)
                self.assertIn("Back to Builder", response.text)
                self.assertIn("Back to Workflows", response.text)
                self.assertIn("Edit workflow", response.text)
                self.assertIn("Open to edit", response.text)
                self.assertIn("Preview with current demo data", response.text)
                self.assertIn("Presentation view", response.text)
                self.assertIn("View report", response.text)
                self.assertIn("renderWorkflowModeSurface", response.text)
                self.assertIn("renderWorkflowModePreview", response.text)
                self.assertIn("preferredPreviewKindForCurrentWorkflow", response.text)
                self.assertIn('data-workflow-action="edit"', response.text)
                self.assertIn('data-workflow-action="populate"', response.text)
                self.assertIn('data-workflow-action="present"', response.text)
                self.assertNotIn('data-workflow-action="open"', response.text)
                self.assertIn("Builder controls, report element finder, JSON tools, and backend save/load controls are not shown here.", response.text)
                self.assertIn("Add at least one client briefing element before previewing.", response.text)
                self.assertIn("Add at least one advisor review element before previewing.", response.text)
                self.assertIn("Copy local workflow JSON", response.text)
                self.assertIn("Download local workflow JSON", response.text)
                self.assertIn("Print", response.text)
                self.assertIn("Export HTML", response.text)
                self.assertIn("Copy text", response.text)
                self.assertIn("Technical local export details", response.text)
                self.assertIn("technical-details", response.text)
                self.assertIn('<details id="serialized-spec-details" class="technical-details">', response.text)
                self.assertIn("Restore local workflow JSON", response.text)
                self.assertIn('<details id="restore-spec-details" class="technical-details">', response.text)
                self.assertIn("Paste exported local workflow JSON", response.text)
                self.assertIn("Restore local workflow", response.text)
                self.assertIn("Backend save/load test controls", response.text)
                self.assertIn("Save to backend", response.text)
                self.assertIn("Load saved sets", response.text)
                self.assertIn("Backend persistence is not configured. Use local workflow JSON export/download for now.", response.text)
                self.assertIn('BRIEFING_SPEC_SETS_ENDPOINT = "/api/briefing-spec-sets"', response.text)
                self.assertIn("saveCurrentSpecSetToBackend", response.text)
                self.assertIn("loadBackendSpecSets", response.text)
                self.assertIn("restoreBackendSpecSet", response.text)
                self.assertIn("QA reference previews", response.text)
                self.assertIn("Open QA Client reference", response.text)
                self.assertIn("Open QA Advisor reference", response.text)
                self.assertIn("This section is not available in the demo preview.", response.text)
                self.assertIn("This element is not previewable yet in the demo. Edit or remove it before previewing.", response.text)
                self.assertIn("Add at least one element before copying local workflow JSON.", response.text)
                self.assertIn("Add at least one element before downloading local workflow JSON.", response.text)
                self.assertIn("Restored ${pluralizeSpec", response.text)
                self.assertIn("arangur.local_briefing_spec_set.v1", response.text)
                self.assertIn("buildLocalSpecSet", response.text)
                self.assertIn("copyCurrentSpecSet", response.text)
                self.assertIn("downloadCurrentSpecSet", response.text)
                self.assertIn("restoreCurrentSpecSet", response.text)
                self.assertIn("openCurrentSetPreview", response.text)
                self.assertIn("@media print", response.text)
                self.assertIn("print-current-preview", response.text)
                self.assertIn("buildCurrentPreviewArtifact", response.text)
                self.assertIn("buildStandalonePreviewHtml", response.text)
                self.assertIn("downloadCurrentPreviewHtml", response.text)
                self.assertIn("copyCurrentPreviewText", response.text)
                self.assertIn("SYNTHETIC_PREVIEW_NOTICE", response.text)
                self.assertIn("SYNTHETIC_PREVIEW_SHORT_NOTICE", response.text)
                self.assertIn("Demo data. Not investment advice.", response.text)
                self.assertIn("new Blob([text]", response.text)
                self.assertIn('downloadTextFile(artifact.standaloneHtml, previewHtmlFilename(kind), "text/html")', response.text)
                self.assertIn("navigator.clipboard.writeText(artifact.text)", response.text)
                self.assertIn("window.print()", response.text)
                self.assertIn('VIEW_SUMMARY_ENDPOINT = "/simulation/report_element_views/report_element_view_summary.json"', response.text)
                self.assertIn('BRIEFING_PREVIEW_INDEX_ENDPOINT = "/simulation/briefing_set_previews/briefing_set_preview_index.json"', response.text)
                self.assertIn("Previewable", response.text)
                self.assertIn("Not previewable yet", response.text)
                self.assertIn("openElementPreview", response.text)
                self.assertIn("renderedViewKeyForSpec", response.text)
                self.assertIn("Use this element", response.text)
                self.assertIn("Add to set as", response.text)
                self.assertIn("Ready to add.", response.text)
                self.assertIn("Choose a scenario to continue.", response.text)
                self.assertIn("Select manager", response.text)
                self.assertIn("Select account", response.text)
                self.assertIn("Select sleeve", response.text)
                self.assertIn("Select strategy", response.text)
                self.assertIn("selected_manager", response.text)
                self.assertIn("selected_account", response.text)
                self.assertIn("selected_sleeve", response.text)
                self.assertIn("selected_strategy", response.text)
                self.assertIn("Choose a manager before adding this element.", response.text)
                self.assertIn("Choose an account before adding this element.", response.text)
                self.assertIn("Choose a sleeve before adding this element.", response.text)
                self.assertIn("PREVIEW_SUPPORTED_SCOPES_BY_ELEMENT", response.text)
                self.assertIn("PREVIEW_SCOPE_NOTES_BY_ELEMENT", response.text)
                self.assertIn("UNSUPPORTED_SELECTED_SCOPE_PREVIEW_MESSAGE", response.text)
                self.assertIn("Selected-scope preview is not available for this demo-rendered element.", response.text)
                self.assertIn('cash_generation_summary: ["Whole portfolio"]', response.text)
                self.assertIn("This template currently previews at the whole-portfolio cash-summary level only.", response.text)
                self.assertIn("previewSupportedScopesForTemplate", response.text)
                self.assertIn("previewScopeNote", response.text)
                self.assertIn("specUsesUnsupportedPreviewScope", response.text)
                self.assertIn("Selected manager:", response.text)
                self.assertIn("selectedEntityTitle", response.text)
                self.assertIn("Client Briefing Workflow", response.text)
                self.assertIn("Advisor Review Workflow", response.text)
                self.assertIn("No client briefing elements yet.", response.text)
                self.assertIn("No advisor review elements yet.", response.text)
                self.assertIn("Client package placement", response.text)
                self.assertIn("Advisor review placement", response.text)
                self.assertIn("Internal purpose", response.text)
                self.assertIn("Scope", response.text)
                self.assertIn("Lens", response.text)
                self.assertIn("Scenario", response.text)
                self.assertIn("Measured by", response.text)
                self.assertIn("Compare by", response.text)
                self.assertIn("Reported as", response.text)
                self.assertIn("Add element", response.text)
                self.assertIn("Promote to Client Briefing", response.text)
                first_screen = self._first_screen(response.text)
                self.assertIn("<strong>Northstar Family Office</strong> &middot; Demo portfolio &middot; Data loaded &middot; Confidence: Mixed &middot; 1 review item", first_screen)
                self.assertIn("Advisor Home", first_screen)
                self.assertIn("Manage briefing workflows", first_screen)
                top_actions = self._between(first_screen, 'id="home-primary-actions"', '<section id="home-create-panel"')
                self.assertEqual(4, top_actions.count("<button"))
                self.assertIn("Create a new workflow", top_actions)
                self.assertIn("Work with an existing workflow", top_actions)
                self.assertIn("Populate a workflow with data", first_screen)
                self.assertIn("Present / view reports", top_actions)
                self.assertIn("Populate a workflow with data", top_actions)
                self.assertNotIn("New Client Briefing Workflow", top_actions)
                self.assertNotIn("New Advisor Review Workflow", top_actions)
                self.assertNotIn("Open saved workflow", top_actions)
                self.assertNotIn("Copy existing workflow", top_actions)
                create_panel = self._between(first_screen, 'id="home-create-panel"', 'id="home-existing-panel"')
                self.assertIn("New Client Briefing Workflow", create_panel)
                self.assertIn("New Advisor Review Workflow", create_panel)
                existing_panel = self._between(first_screen, 'id="home-existing-panel"', 'id="home-populate-panel"')
                self.assertIn("home-saved-workflow-list", existing_panel)
                self.assertIn("Open a browser-local saved workflow to edit its design, or copy/delete saved drafts.", existing_panel)
                populate_panel = self._between(first_screen, 'id="home-populate-panel"', 'id="home-present-panel"')
                self.assertIn("home-populate-workflow-list", populate_panel)
                self.assertIn("Choose a saved workflow, bind it to the current demo data snapshot, and preview it locally.", populate_panel)
                self.assertIn("Full dated report generation and persistence are not implemented yet.", populate_panel)
                present_panel = self._between(first_screen, 'id="home-present-panel"', '<details class="developer-tools-panel">')
                self.assertIn("home-present-workflow-list", present_panel)
                self.assertIn("Choose a saved workflow and open a clean Presentation view using the current demo preview renderer.", present_panel)
                self.assertIn("Developer / QA tools", first_screen)
                self.assertNotIn("Open Saved Set / Continue Draft", first_screen)
                self.assertNotIn("Build Client Briefing Set", first_screen)
                self.assertNotIn("Build Advisor Review Set", first_screen)
                self.assertNotIn("Report element finder", first_screen)
                self.assertNotIn("Choose a target set, then find an element", first_screen)
                self.assertNotIn("Search report elements", first_screen)
                self.assertNotIn("Browse all templates", first_screen)
                self.assertNotIn("Add narrative element", first_screen)
                self.assertNotIn("Search, browse a category, or choose a filter to find report elements.", first_screen)
                self.assertNotIn("Select a report element to see details.", first_screen)
                self.assertNotIn("home-preview-client-button", first_screen)
                self.assertNotIn("home-preview-advisor-button", first_screen)
                self.assertNotIn("Add at least one client briefing element before previewing.", first_screen)
                self.assertNotIn("Add at least one advisor review element before previewing.", first_screen)
                self.assertNotIn("Copy local set JSON", first_screen)
                self.assertNotIn("Download local set JSON", first_screen)
                self.assertNotIn("Backend save/load", first_screen)
                self.assertNotIn("QA reference previews", first_screen)
                self.assertNotIn("Print", first_screen)
                self.assertNotIn("Export HTML", first_screen)
                self.assertNotIn("Copy text", first_screen)
                self.assertNotIn("Which report branch is this element for?", first_screen)
                self.assertNotIn("<label for=\"config-branch\">", response.text)
                self.assertNotIn("Portfolio Status", first_screen)
                self.assertNotIn("Scenario Impact by Manager", first_screen)
                self.assertNotIn("What should this report focus on?", first_screen)
                self.assertNotIn("Last updated: Demo fixture", first_screen)
                self.assertNotIn("Recent briefings", first_screen)
                self.assertNotIn("Run workflow", response.text)
                self.assertNotIn("Technical/Admin Appendix", response.text)
                self.assertNotIn(".json", first_screen)
                self.assertNotIn("Sample previews", response.text)
                self.assertNotIn("No rendered preview available yet for this spec.", response.text)
                self.assertNotIn("report_package.json", first_screen)
                self.assertNotIn("report_package", response.text)
                self.assertNotIn("/api/runs", response.text)

    def test_browser_report_element_composer_fetches_catalog_and_preview_artifacts_only(self) -> None:
        client = TestClient(create_app(settings=AppSettings()))
        response = client.get("/app/")
        self.assertEqual(200, response.status_code)
        self.assertIn("/api/report-elements", response.text)
        self.assertIn("/simulation/report_element_views/report_element_view_summary.json", response.text)
        self.assertIn("/simulation/briefing_set_previews/briefing_set_preview_index.json", response.text)
        self.assertIn("/simulation/briefing_set_previews/client_briefing_set_preview.html", response.text)
        self.assertIn("/simulation/briefing_set_previews/advisor_review_set_preview.html", response.text)
        self.assertIn("fetch(CATALOG_ENDPOINT)", response.text)
        self.assertIn("fetch(BRIEFING_SPEC_SETS_ENDPOINT", response.text)
        self.assertIn("fetch(VIEW_SUMMARY_ENDPOINT)", response.text)
        self.assertIn("fetch(BRIEFING_PREVIEW_INDEX_ENDPOINT)", response.text)
        self.assertIn("LOCAL_SPEC_SET_SCHEMA_VERSION", response.text)
        self.assertIn("Preview Client Briefing", response.text)
        self.assertIn("Preview Advisor Review", response.text)
        self.assertIn("Back to Builder", response.text)
        self.assertIn("Developer / QA tools", response.text)
        self.assertIn("Technical local export details", response.text)
        self.assertIn("Restore local workflow JSON", response.text)
        self.assertIn("Backend save/load test controls", response.text)
        self.assertIn("Export HTML", response.text)
        self.assertIn("Copy text", response.text)
        self.assertIn("@media print", response.text)
        self.assertIn("buildStandalonePreviewHtml", response.text)
        self.assertIn("downloadTextFile", response.text)
        self.assertIn("Add at least one element before downloading local workflow JSON.", response.text)
        self.assertNotIn("/api/runs", response.text)
        self.assertNotIn("report_package", response.text)
        self.assertNotIn("reports/demo/index", response.text)
        self.assertNotIn("Sample previews", response.text)
        self.assertNotIn("No rendered preview available yet for this spec.", response.text)
        first_screen = self._first_screen(response.text)
        self.assertNotIn(".json", first_screen)
        self.assertNotIn("Copy local workflow JSON", first_screen)
        self.assertNotIn("Backend save/load", first_screen)
        self.assertNotIn("QA reference previews", first_screen)
        self.assertNotIn("Export HTML", first_screen)
        self.assertNotIn("Run workflow", response.text)
        self.assertIn("Search report elements", response.text)
        self.assertIn("Add element", response.text)
        self.assertIn("Browse all templates", response.text)
        self.assertIn("Add narrative element", response.text)

    def test_simulation_artifacts_are_served_from_safe_static_mount(self) -> None:
        client = TestClient(create_app(settings=AppSettings()))

        view_summary = client.get("/simulation/report_element_views/report_element_view_summary.json")
        self.assertEqual(200, view_summary.status_code)
        self.assertEqual("report_element_view_summary.v1", view_summary.json()["schema_version"])
        self.assertEqual(7, view_summary.json()["view_count"])

        preview_index = client.get("/simulation/briefing_set_previews/briefing_set_preview_index.json")
        self.assertEqual(200, preview_index.status_code)
        self.assertEqual("briefing_set_preview_index.v1", preview_index.json()["schema_version"])
        self.assertEqual(2, preview_index.json()["preview_count"])

        element_fragment = client.get("/simulation/report_element_views/portfolio_status.html")
        self.assertEqual(200, element_fragment.status_code)
        self.assertIn("Portfolio Status", element_fragment.text)

        sample_preview = client.get("/simulation/briefing_set_previews/client_briefing_set_preview.html")
        self.assertEqual(200, sample_preview.status_code)
        self.assertIn("Client Briefing Set Preview", sample_preview.text)

        escaped_root_file = client.get("/simulation/../README.md")
        self.assertEqual(404, escaped_root_file.status_code)

    def test_lens_options_do_not_include_plain_manager(self) -> None:
        client = TestClient(create_app(settings=AppSettings()))
        response = client.get("/app/")
        self.assertEqual(200, response.status_code)
        html = response.text
        self.assertNotIn("const lensOptions", html)
        self.assertNotIn('value="Manager"', html)
        self.assertNotIn(">Manager</option>", html)
        self.assertIn('lens !== "Manager"', html)

    def test_report_element_finder_does_not_show_universal_form_or_full_catalog_first(self) -> None:
        client = TestClient(create_app(settings=AppSettings()))
        response = client.get("/app/")
        self.assertEqual(200, response.status_code)
        first_screen = self._first_screen(response.text)
        self.assertNotIn("candidate-card", response.text)
        self.assertNotIn("fixed-fields", response.text)
        self.assertNotIn("Display form", response.text)
        self.assertNotIn("<label for=\"config-branch\">", response.text)
        self.assertIn("browse-picker", response.text)
        self.assertIn("browse-category-row", response.text)
        self.assertIn("browse-template-row", response.text)
        self.assertIn("Browse all templates", response.text)
        self.assertNotIn("Portfolio Status", first_screen)
        self.assertNotIn("Cash Generation Summary", first_screen)
        self.assertNotIn("Data Confidence Note", first_screen)
        self.assertIn("Use this element", response.text)
        self.assertIn("Template details", response.text)

    def test_narrative_elements_are_supported_in_same_set_lists(self) -> None:
        client = TestClient(create_app(settings=AppSettings()))
        response = client.get("/app/")
        self.assertEqual(200, response.status_code)
        self.assertIn("NARRATIVE_TYPES", response.text)
        self.assertIn("NARRATIVE_PLACEMENTS", response.text)
        self.assertIn("startNarrativeElement", response.text)
        self.assertIn("renderNarrativeSetRow", response.text)
        self.assertIn("is-narrative", response.text)
        self.assertIn("Title text", response.text)
        self.assertIn("Body text", response.text)
        self.assertIn("Prompt text", response.text)
        self.assertIn("Note text", response.text)

    def test_static_app_embedded_javascript_parses(self) -> None:
        node = shutil.which("node")
        if not node:
            self.skipTest("node is not available for embedded JavaScript parse smoke")
        html = (ROOT / "src" / "arangur" / "app" / "static" / "index.html").read_text(encoding="utf-8")
        scripts = re.findall(r"<script>(.*?)</script>", html, flags=re.DOTALL)
        self.assertEqual(1, len(scripts))
        result = subprocess.run(
            [node, "--check", "-"],
            input=scripts[0],
            capture_output=True,
            check=False,
            text=True,
        )
        self.assertEqual(0, result.returncode, result.stderr)

    def _first_screen(self, html: str) -> str:
        start_marker = "<!-- first-screen-start -->"
        end_marker = "<!-- first-screen-end -->"
        self.assertIn(start_marker, html)
        self.assertIn(end_marker, html)
        return html[html.index(start_marker) : html.index(end_marker)]

    def _between(self, html: str, start_marker: str, end_marker: str) -> str:
        self.assertIn(start_marker, html)
        self.assertIn(end_marker, html)
        start = html.index(start_marker)
        end = html.index(end_marker, start)
        return html[start:end]


if __name__ == "__main__":
    unittest.main()
